spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: system
    password: engenharia
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        # Default schema for Oracle
        default_schema: FIAP
    show-sql: true

  flyway:
    enabled: false # Disable Flyway for now
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  packages-to-scan: br.com.fiap.supplychainapi.controller

security:
  jwt:
    secret: S3cr3tK3yForJWTGeneration
    expiration: 3600000
