-- Create users table
CREATE TABLE FIAP.USERS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create products table
CREATE TABLE FIAP.PRODUCTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PRICE NUMBER(10, 2) NOT NULL,
    STOCK_QUANTITY NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create orders table
CREATE TABLE FIAP.ORDERS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(10, 2) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES FIAP.USERS(ID)
);

-- Create order_items table
CREATE TABLE FIAP.ORDER_ITEMS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    UNIT_PRICE NUMBER(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES FIAP.ORDERS(ID),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES FIAP.PRODUCTS(ID)
);

-- Create suppliers table
CREATE TABLE FIAP.SUPPLIERS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    SUSTAINABLE_PRACTICES_SCORE NUMBER,
    FAIR_LABOR_SCORE NUMBER,
    CERTIFICATION_STATUS VARCHAR2(50),
    LAST_AUDIT_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create carbon_footprints table
CREATE TABLE FIAP.CARBON_FOOTPRINTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUPPLIER_ID NUMBER NOT NULL,
    EMISSION_DATE TIMESTAMP NOT NULL,
    PRODUCTION_EMISSIONS NUMBER(10, 2) NOT NULL,
    TRANSPORTATION_EMISSIONS NUMBER(10, 2) NOT NULL,
    EMISSION_SOURCE VARCHAR2(200),
    MITIGATION_MEASURES VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CARBON_FOOTPRINT_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES FIAP.SUPPLIERS(ID)
);

-- Create compliance_reports table
CREATE TABLE FIAP.COMPLIANCE_REPORTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUPPLIER_ID NUMBER NOT NULL,
    REPORT_DATE TIMESTAMP NOT NULL,
    COMPLIANCE_SCORE NUMBER,
    SUSTAINABILITY_RATING VARCHAR2(20),
    LABOR_PRACTICES_RATING VARCHAR2(20),
    ENVIRONMENTAL_IMPACT_RATING VARCHAR2(20),
    RECOMMENDATIONS VARCHAR2(500),
    STATUS VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMPLIANCE_REPORT_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES FIAP.SUPPLIERS(ID)
);