spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: system
    password: engenharia
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        # Default schema for Oracle
        default_schema: FIAP
    show-sql: true

  flyway:
    enabled: false # Disable Flyway for now
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

security:
  jwt:
    secret: S3cr3tK3yForJWTGeneration
    expiration: 3600000
